nexus/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from tastypie.api import Api

from .views import (home, assigned_appraisals, all_appraisals,
                    edit_engagement, edit_engagement_property,
                    all_clients, view_client, edit_amf,
                    view_property, view_appraisal, view_portfolio,
                    view_work_in_progress, view_work_in_progress_csv,
                    view_state_licensing, view_license_info,
                    employee_appraisals,)
from . import api


admin.autodiscover()

# Register Tastypie resources to the API.
v1_api = Api(api_name='v1')
v1_api.register(api.AddressResource())
v1_api.register(api.AMFResource())
v1_api.register(api.EngagementPropertyResource())
v1_api.register(api.AppraisalOccurrenceScheduleResource())
v1_api.register(api.ScheduledAssignmentResource())
v1_api.register(api.AssignmentResource())
v1_api.register(api.ScheduledAppraisalResource())
v1_api.register(api.AppraisalResource())
v1_api.register(api.AppraisalResourceThin())
v1_api.register(api.AppraisalStatusChangeResource())
v1_api.register(api.ClientResource())
v1_api.register(api.ContactResource())
v1_api.register(api.EmployeeResource())
v1_api.register(api.EngagementResource())
v1_api.register(api.LicenseResource())
v1_api.register(api.LicenseRequirementsResource())
v1_api.register(api.OfficeResource())
v1_api.register(api.PortfolioResource())
v1_api.register(api.PropertyResource())
v1_api.register(api.ZipcodeResource())


urlpatterns = patterns(
    '',

    # landing pages
    url(r'^$', home),
    url(r'^assigned-appraisals/$', assigned_appraisals),
    url(r'^appraisals/$', all_appraisals),
    url(r'^employee-appraisals/$', employee_appraisals),

    # engagement
    url(r'^engagement/property/(?P<prop_id>.+)$', edit_engagement_property),
    url(r'^engagement/$', edit_engagement),
    url(r'^engagement/(?P<engagement_id>.+)$', edit_engagement),

    # property
    url(r'^property/(?P<property_id>.+)$', view_property),

    # appraisal
    url(r'^appraisal/(?P<appraisal_id>.+)$', view_appraisal),

    # portfolio
    url(r'^portfolio/(?P<portfolio_id>.+)$', view_portfolio),

    # work in progress
    url(r'^work-in-progress/$', view_work_in_progress),
    url(r'^work-in-progress-csv/$', view_work_in_progress_csv),


    # client/amf
    url(r'^clients/$', all_clients),
    url(r'^client/(?P<client_id>.+)$', view_client),
    url(r'^amf/$', edit_amf),
    url(r'^amf/(?P<amf_id>.+)$', edit_amf),

    # license info
    url(r'^state-licensing/$', view_state_licensing),
    url(r'^license-info/(?P<state>.+)$', view_license_info),

    # Tastypie api
    url(r'^api/', include(v1_api.urls)),

    # admin
    url(r'^admin/', include(admin.site.urls)),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # authentication
    url(r'^employees/login/', 'django.contrib.auth.views.login'),
    url(r'^logout/', 'django.contrib.auth.views.logout',
        {'next_page': '/employees/login/'}),
)


if settings.DEBUG:
    from django.views.generic import TemplateView

    urlpatterns += patterns(
        '',
        url(r'^404.html$', TemplateView.as_view(template_name='404.html'))
    )

nexus/models.py
import logging
from datetime import date, datetime, timedelta

from django.conf import settings
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models import Sum
from django.db.models.signals import pre_save, post_save, pre_delete
from django.dispatch import receiver
from django.contrib.auth import models as auth_models
from django_google_maps import fields as map_fields

from .utils import date_range_for_quarter


log = logging.getLogger('nexus')

property_ = property


class ChoicesEnum(object):
    """
    Abstract base class for enumerated types used as 'choices' fields.

    Subclasses must define an 'all' property that is a list of all the values.
    """

    @classmethod
    def as_choices(cls):
        """List of value+label tuples usable for Django ORM 'choices'."""
        choices = []
        for val in cls.all:
            label = ' '.join(w.capitalize() for w in val.split('_'))
            choices.append((val, label))
        return choices


class TimestampedMixin(models.Model):
    """A Model mixin that adds auto set created and changed fields."""
    created = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    changed = models.DateTimeField(auto_now=True, null=True, blank=True)

    class Meta:
        abstract = True


def timestamp_pre_save(sender, instance, *args, **kwargs):
    """Model pre_save signal handler ensuring created/changed are set."""
    if hasattr(instance, 'created') and not instance.created:
        instance.created = datetime.now()
    if hasattr(instance, 'changed') and not instance.changed:
        instance.changed = datetime.now()

pre_save.connect(timestamp_pre_save)


class NexusModel(models.Model):
    """A base Model class for models optionally persisted by a given user."""

    class Meta:
        abstract = True

    def save(self, *args, **kwargs):
        self.full_clean()
        super(NexusModel, self).save(*args, **kwargs)


class Client(TimestampedMixin, NexusModel):
    name = models.CharField(max_length=64)
    notes = models.TextField(max_length=512, blank=True, null=True)
    appraiser_must_sign = models.BooleanField(default=False)
    appraiser_must_inspect = models.BooleanField(default=False)
    requirements_url = models.URLField(null=True, blank=True)
    invoice_delivery = models.CharField(max_length=128, null=True, blank=True)
    report_delivery = models.CharField(max_length=128, null=True, blank=True)

    TIMING_TYPES = (
        ('DRAFT', 'With Draft'),
        ('FINAL', 'With Final'),
        ('END_OF_QUARTER', 'End of Quarter'),
        ('OTHER', 'Other'),
    )
    invoice_timing = models.CharField(max_length=16, choices=TIMING_TYPES,
                                      default='OTHER')
    CLIENT_TYPES = (
        ('BANK', 'Bank'),
        ('PENSION_FUND', 'Pension Fund'),
        ('LIFE_COMPANY', 'Life Company'),
        ('CORPORATE', 'Corporate'),
        ('DEVELOPER', 'Developer'),
        ('PRIVATE_INVESTOR', 'Private Investor'),
        ('HEDGE_FUND', 'Hedge Fund'),
        ('LAW_FIRM', 'Law Firm'),
        ('OTHER', 'Other'),
    )
    client_type = models.CharField(max_length=16,
                                   choices=CLIENT_TYPES,
                                   default='BANK')

    def __unicode__(self):
        return u'%s' % (self.name)

    class Meta:
        ordering = ['name', ]

    @property
    def uri(self):
        from .api import ClientResource
        return ClientResource().get_resource_uri(self)

    def get_absolute_url(self):
        return '/client/{}'.format(self.pk)

    def json(self):
        from api import ClientResource
        res = ClientResource()
        bundle = res.build_bundle(obj=self)
        return res.serialize(None, res.full_dehydrate(bundle),
                             'application/json')

    def get_engagements(self):
        """Retrieve all engagements for this client"""
        return self.client_engagements.all()

    def get_active_appraisals(self):
        """Retrieve all active appraisals for this client"""
        return Appraisal.objects.filter(
            engagement_property__property__client=self).\
            exclude(status__in=['COMPLETED', 'CANCELLED'])

    def get_historical_appraisals(self):
        """Retrieve all historical appraisals for this client"""
        return Appraisal.objects.filter(
            engagement_property__property__client=self).\
            filter(status__in=['COMPLETED'])

    def get_appraisals(self, start_date=None, end_date=None):
        """Retrieve all appraisals for this client"""
        kwargs = {}
        kwargs['engagement_property__property__client'] = self
        if start_date:
            kwargs['due_date__gte'] = start_date
        if end_date:
            kwargs['due_date__lte'] = end_date
        return Appraisal.objects.filter(**kwargs).\
            exclude(status__in=['CANCELLED'])

    def get_appraisal_fee_sum(self, start_date=None, end_date=None):
        """Retrieve the appraisal fee sum for this client"""
        kwargs = {}
        kwargs['engagement_property__property__client'] = self
        if start_date:
            kwargs['due_date__gte'] = start_date
        if end_date:
            kwargs['due_date__lte'] = end_date
        fee_sum_dict = Appraisal.objects.filter(**kwargs).\
            aggregate(Sum('fee'))
        return fee_sum_dict['fee__sum'] if fee_sum_dict['fee__sum'] else 0

    def get_states(self, start_date=None, end_date=None):
        """Retrieve all states for this client"""
        state_list = []
        kwargs = {}
        kwargs['engagement_property__property__client'] = self
        if start_date:
            kwargs['due_date__gte'] = start_date
        if end_date:
            kwargs['due_date__lte'] = end_date
        appraisals = Appraisal.objects.filter(**kwargs).\
            exclude(status__in=['CANCELLED'])
        for appraisal in appraisals:
            states = appraisal.engagement_property.\
                property.address_set.values_list('state', flat=True)
            for state in states:
                if state not in state_list:
                    state_list.append(state)
        return state_list


class AMF(TimestampedMixin, NexusModel):
    name = models.CharField(max_length=128)

    def __unicode__(self):
        return self.name

    @property
    def uri(self):
        from .api import AMFResource
        return AMFResource().get_resource_uri(self)

    def get_absolute_url(self):
        return '/amf/{}'.format(self.pk)

    class Meta:
        ordering = ['name']

    def get_appraisals(self):
        a_apps = []
        for e in Engagement.objects.filter(amf=self.pk):
            if e.property is not None:
                qs = e.property.appraisal_set.all().exclude(status='COMPLETED')
                for a in qs:
                    a_apps.append(a)
            else:  # there is a portfolio
                for p in e.portfolio.property_set.all():
                    for a in p.appraisal_set.all().exclude(status='COMPLETED'):
                        a_apps.append(a)
        return a_apps

    def get_historical_appraisals(self):
        h_apps = []
        for e in Engagement.objects.filter(client=self.pk):
            if e.property is not None:
                for a in e.property.appraisal_set.filter(status='COMPLETED'):
                    h_apps.append(a)
            else:  # there is a portfolio
                for p in e.portfolio.property_set.all():
                    qs = e.property.appraisal_set.filter(status='COMPLETED')
                    for a in qs:
                        h_apps.append(a)
        return h_apps


class Portfolio(TimestampedMixin, NexusModel):
    name = models.CharField(max_length=64)
    notes = models.TextField(max_length=512, null=True, blank=True)
    client = models.ForeignKey('Client', null=True, blank=True)
    client_contact = models.ForeignKey('Contact', null=True, blank=True)

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ['client', 'name']

    @property
    def uri(self):
        from .api import PortfolioResource
        return PortfolioResource().get_resource_uri(self)

    def get_absolute_url(self):
        return '/portfolio/{}'.format(self.pk)

    def get_appraisals(self):
        properties = self.property_set.all()
        return Appraisal.objects.filter(
            engagement_property__property__in=properties).\
            exclude(status__in=['COMPLETED',
                                'CANCELLED'])

    def get_aggregate_fee(self):
        return self.get_appraisals().aggregate(Sum('fee'))

    def get_historical_appraisals(self):
        properties = self.property_set.all()
        return Appraisal.objects.filter(
            engagement_property__property__in=properties,
            status='COMPLETED')


class Property(TimestampedMixin, NexusModel):
    name = models.CharField(max_length=128)
    federally_related = models.BooleanField(default=False)
    client_asset_number = models.CharField(max_length=128, null=True,
                                           blank=True)
    notes = models.TextField(max_length=512, null=True, blank=True)
    proposed = models.BooleanField(default=False)
    contact = models.ForeignKey('Contact', null=True, blank=True)
    portfolio = models.ForeignKey('Portfolio', null=True, blank=True)
    # QQQ: Should client be nullable for Property in a Portfolio case?
    client = models.ForeignKey('Client', null=True, blank=True)

    PROPERTY_TYPE = (
        ('Industrial', 'Industrial'),
        ('Office', 'Office'),
        ('Hospitality', 'Hospitality'),
        ('Health Care', 'Health Care'),
        ('Retail', 'Retail'),
        ('Specialty', 'Specialty'),
        ('Flex', 'Flex'),
        ('Multi-Family', 'Multi-Family'),
        ('Land', 'Land'),
        ('Other', 'Other'),
    )

    property_type = models.CharField(max_length=32, choices=PROPERTY_TYPE,

nexus/templates/clients.html
{% extends "base.html" %}

{% block htmlhead %}
{% load custom_tags %}

{% endblock %}

{% block body %}
<div class="container view-client-list">
    <h2>Clients - 2014 YTD </h2>
    <div class="count">Showing <b>{{ clients|length }}</b> records</div>
    <table id='ModelTable' class='table table-striped footable'>
        <thead>
            <tr>
                <th data-class="expand">Client</th>
                <!--<th class="footable-sortable" data-hide="phone,tablet" data-type="numeric">Engagements</th>-->
                <th data-type="numeric" data-hide="phone">Appraisals <i class="glyphicon glyphicon-info-sign tooltipicon" data-toggle="tooltip" data-placement="top" title="Total number of appraisals for each client"></i></th>
                <th data-type="numeric">Fee Sum <i class="glyphicon glyphicon-info-sign tooltipicon" data-toggle="tooltip" data-placement="top" title="Total sum of all appraisal fees for each client"></i></th>
                <th data-hide="phone,tablet" data-type="numeric">States <i class="glyphicon glyphicon-info-sign tooltipicon" data-toggle="tooltip" data-placement="top" title="Number of states covered by appraisals for each client"></i></th>
                <th data-hide="phone,tablet">Type</th>
            </tr>
        </thead>
        <tbody>
            {% for client in clients %}
       
            <tr>
                <td><a href="{{ client.get_absolute_url }}">{{ client.name }}</a></td>
                <td>{{ client.num_appraisals }}</td>
                <td data-value="{{ client.fee_sum }}">{{ client.fee_sum|currency }}</td>
                <td>{{ client.num_states }}</td>
                <td>{{ client.get_client_type_display }}</td>
            </tr>
            {% endfor %}
   
        </tbody>
    </table>
</div>
{% endblock %}
{% block bodyend %}
<script>
    NPVNexus.View_Client_List.init();
</script>
{% endblock %}

nexus/templates/edit_client.html
{% extends "base.html" %}

{% block page_title %} - {{ appraisal.property.name }}{% endblock %}

{% block htmlhead %}


{% endblock %}

{% block body %}


<div class="container edit-amf">
    <h2>Edit AMF/Client</h2>
    <form id="AmfForm" action="{{ amf.uri }}" role="form" class="form-horizontal">


        <div class="form-group">
            <label class="col-xs-3 control-label">AMF Name</label>
            <div class="col-xs-7">
            <input type="text" id="Amfname" class="name form-control" value="" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-xs-12">
                <input type="submit" id="Save" class="form-control npvBtn pullRight" value="Save" />
            </div>
        </div>
    </form>
</div>

{% endblock %}

{% block bodyend %}
<script src="{{ STATIC_URL }}lib/backbone/backbone-min.js"></script>
<script src="{{ STATIC_URL }}lib/cocktail/Cocktail.min.js"></script>
<script src="{{ STATIC_URL }}common_bb.js"></script>
<script src="{{ STATIC_URL }}client.js"></script>
<script>
    //amf = {{amf|safe}};
    $(document).ready(function(){
        window.app = new npv.AmfEditView({{ clients|default:''|safe }});
    });
</script>
{% endblock %}

nexus/templates/edit_property.html
{% extends "base.html" %}

{% block page_title %} - {{ appraisal.property.name }}{% endblock %}

{% block htmlhead %}


{% endblock %}

{% block body %}

<div class="container">
    <h2>Edit Property</h2>
</div>

{% endblock %}

{% block bodyend %}
{% endblock %}

nexus/templates/view_client.html
{% extends "base.html" %}

{% block page_title %} - {{ client.name }}{% endblock %}

{% block htmlhead %}
{% load custom_tags %}

{% endblock %}

{% block body %}

<div class="container view-client">
	<div class="row">
    <div class="col-md-12">
        <h2 >{{ client.name }}</h2>
        <h4>Type: <small>{{ client.get_client_type_display }}</small></h4>
        <h3>Instructions</h3>
    </div>
	</div>
    <div class="row">
    <div class="col-md-6">
            <table class="table reqTable">
                <tr>
                    <td><label for="appraiser_sign">Appraiser Must Sign?</label></td>
                    <td><input type="checkbox" id="AppraiserSign"
                    {% if client.appraiser_must_sign %} checked />
                    {% else %} />
                    {% endif %}
                    </td>
                </tr>
                <tr>
                    <td><label for="appraiser_inspect">Appraiser Must Inspect?</label></td>
                    <td><input type="checkbox" id="AppraiserInspect"
                    {% if client.appraiser_must_inspect %} checked />
                    {% else %} />
                    {% endif %}
                    </td>
                </tr>
                <tr>
                    <td colspan="2">
                    <label for="client_requirements">Client Requirements</label>
                    <input type="text" class="form-control" id="ClientRequirements" 
                       {% if client.requirements_url %} value='{{ client.requirements_url }}' {% endif %} />
                        <a href=" {{ client.requirements_url }}" id="ViewReq"  {% if client.requirements_url %}style="display:inline-block" {% endif %} target="_blank" class="npvBtn form-control">View Requirements</a>
                    </td>
                </tr>
                <tr>
                    <td colspan="2">
                    <label for="client_notes">Client Notes</label>
                    <textarea class="form-control" id="ClientNotes" cols="3"
                        >{% if client.notes %}{{ client.notes }}{% endif %}</textarea>
                    </td>
                </tr>
            </table>
    </div>
    <div class="col-md-6">
            <table class="table reqTable">
                <tr>
                    <td>
                    <label for="invoice_delivery">Invoice Delivery</label>
                    <textarea cols="3" class="form-control" id="InvoiceDelivery" 
                       >{% if client.invoice_delivery %}{{ client.invoice_delivery }}{% endif %}</textarea>
                    </td>
                </tr>
                <tr>
                    <td>
                    <label for="report_delivery">Report Delivery</label>
                    <input type="text" class="form-control" id="ReportDelivery" 
                        {% if client.report_delivery %} value="{{ client.report_delivery }}" {% endif %}>
                    </td>
                </tr>
                <tr>
                    <td>
                        <label for="invoice_timing">Invoice Timing</label>
                        <select class='form-control npvSelect' id='InvoiceTiming'>
                            <option value="DRAFT"
                            {% if client.invoice_timing == "DRAFT" %} selected="true"
                            {% endif %}
                            >With Draft</option>

                            <option value="FINAL"
                            {% if client.invoice_timing == "FINAL" %} selected="true"
                            {% endif %}
                            >With Final</option>

                            <option value="END_OF_QUARTER"
                            {% if client.invoice_timing == "END_OF_QUARTER" %} selected="true"
                            {% endif %}
                            >End of Quarter</option>

                            <option value="OTHER"
                            {% if client.invoice_timing == "OTHER" %} selected="true"
                            {% endif %}
                            >Other</option>
                        </select>
                    </td>
                </tr>
            </table>
    </div>
        </div>
    <div class="row">
        <div class="col-sm-12">
            <button id='Update' type='submit' action="/api/v1/client/{{ client.pk }}/"
                class="btn btn-sm npvBtn pull-right" >Update</button>
        </div>
    </div>
    <div class="row">
    <div class="col-md-12">
        <h3>Contacts</h3>
        <table id='Contacts' class='table table-striped footable'>
            <thead> 
            <tr>
                <th data-class="expand">Name</th>
                <th data-hide="phone,tablet">Email</th>
                <th>Phone</th>
                <th ata-hide="phone">Mobile</th>
                <th data-hide="phone,tablet">Fax</th>
                <th data-hide="phone,tablet">Address</th>
            </tr>
            </thead>
            <tbody>
            {% for contact in client.contacts.all %}
            <tr>
                <td>{{ contact }}</td>
                <td>{{ contact.email }}</td>
                <td>{% phonenumber contact.phone %}</td>
                <td>{% phonenumber contact.mobile %}</td>
                <td>{% phonenumber contact.fax %}</td>
                <td>{{ contact.address }}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
        </div>
    <div class="row">
    <div class="col-md-12">
        <h3>Properties/Appraisals</h3>
        <div  class="btn-group">
            <button type="button" class="btn btn-default active" id="BtnActive">Active</button>
            <button type="button" class="btn btn-default" id="BtnHistorical">Historical</button>
        </div>
        <table id='Active' class='table table-striped footable'>
            <thead> 
            <tr>
                <th data-hide="phone,tablet">Job Number</th>
                <th data-class="expand">Property</th>
                <th data-hide="phone">Appraiser</th>
                <th>Due Date</th>
                <th data-hide="phone,tablet">Final Value</th>
                <th data-type="numeric">Fee</th>
                <th data-hide="phone,tablet">Status</th>
            </tr>
            </thead>
            <tbody>
            {% for appraisal in client.get_active_appraisals %}
            <tr>
                <td><a href="{{ appraisal.get_absolute_url }}">{{ appraisal.job_number }}</a></td>
                <td><a href="/property/{{ appraisal.engagement_property.property.id }}">{{ appraisal.engagement_property.property }}</a></td>
                <td>{{ appraisal.lead_appraiser.employee.name|default:'' }}</td>
                <td>{{ appraisal.due_date }}</td>
                <td>${{ appraisal.final_value }}</td>
                <td data-value="{{ appraisal.fee }}">{{ appraisal.fee|currency }}</td>
                <td>{{ appraisal.get_status_display }}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
        <table id='Historical' class='table table-striped footable'>
            <thead> 
            <tr>
                <th data-hide="phone,tablet">Job Number</th>
                <th data-class="expand">Property</th>
                <th data-hide="phone">Appraiser</th>
                <th>Due Date</th>
                <th data-hide="phone,tablet">Final Value</th>
                <th data-type="numeric">Fee</th>
                <th data-hide="phone,tablet">Status</th>
            </tr>
            </thead>
            <tbody>
            {% for appraisal in client.get_historical_appraisals %}
            <tr>
                <td><a href="{{ appraisal.get_absolute_url }}">{{ appraisal.job_number }}</a></td>
                <td><a href="/property/{{ appraisal.engagement_property.property.id }}">{{ appraisal.engagement_property.property }}</a></td> 
                <td>{{ appraisal.lead_appraiser.employee.name|default:'' }}</td>
                <td>{{ appraisal.due_date }}</td>
                <td>${{ appraisal.final_value }}</td>
                <td data-value="{{ appraisal.fee }}">{{ appraisal.fee|currency }}</td>
                <td>{{ appraisal.get_status_display }}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
     </div>
   </div>
</div>

{% endblock %}

{% block bodyend %}
<script>
    NPVNexus.View_Client.init();
</script>

{% endblock %}

nexus/templates/view_property.html
{% extends "base.html" %}

{% block page_title %} - {{ property.name }}{% endblock %}

{% block htmlhead %}
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDFaC5ulx84d9aO14GRv4EdJ2W-W7fCMJE&sensor=true"></script>

{% endblock %}

{% block body %}
{% load custom_tags %}
<div class="container view_property">
<!--########### Start Top Row ###########-->
    <div class="row">
        <div class="col-sm-8">
            <h2>{% if property.portfolio %}
        <a href="{{ property.portfolio.get_absolute_url }}">{{ property.portfolio }}</a>
                {% endif %}
                {{ property.name }}</h2>
            <ul class="addresses">
            {% for address in property.address_set.all %}
                <li class="addy">
                {{ address.address1 }}
                {% if address.address2 %}{{ address.address2 }} {% endif %}
                {{ address.city }}, {{ address.state }} {{ address.zipcode }}
                </li>
            {% endfor %}
            </ul>
            <h4 class="left">Type: <span>{{ property.get_property_type_display }}</span></h4>
            {% if property.property_subtype %}
            <h4 class="right">Subtype: <span>{{ property.property_subtype }}</span></h4>
            {% endif %}
        </div>
        <div class="col-sm-4">
        <!--    {% if fee %}<h4>Value: <span>{{fee|currency}}</span></h4>{% endif %}-->
        </div>
    </div>
<!--########### End Top Row ###########-->
<!--########### Start Middle Row ###########-->
    <div class="row">
        <div class="col-md-4 col-sm-6">
        <!--Start Map-->
            <div id="MapCanvas">
            {% if property.address_set %}
                <img src="/static/images/nexusV1/No-Address.jpg" />
            {% endif %}
            </div>
        <!--End Map-->
        </div>
    <div class="col-md-4 col-sm-6">
    {% if property.client %}
     <table class="footable contentCollapse table">
        <thead>
            <tr>
                <th data-class="expand" data-sort-ignore="true"></th>
                <th data-hide="phone,tablet">Contacts</th>
                <th data-hide="phone,tablet">Requirements</th>
            </tr>
        </thead>
        <tbody>
            <tr>
            <td><h4>Client: <a href="{{ property.client.get_absolute_url }}">{{ property.client.name }}</a></h4></td>
            <td>
                <ul>
                {% for contact in property.client.contacts.all %}
                    <li><a href="{{ property.client.get_absolute_url }}">{{ contact }}</a></li>
                {% endfor %}
                </ul>
            </td>
                {% if property.client.requirements_url  %} 
            <td><a target="_blank" href="{{ property.client.requirements_url }}">Client Requirements</a></td>
                {% endif %}
            </tr>
            </tbody>
        </table>
    {% endif %}
    {% if property.contact %}
    <h4>Contact: {{ property.contact }}</h4>
    {% endif %}
    </div>
    <div class="col-md-4 col-sm-6">
    {% if property.notes %}
    <h4>Notes:</h4>
    <p>{{ property.notes }}</p>
    {% endif %}
    </div>
    </div>
    <!--########### End Middle Row ###########-->
    <!--########### Start Bottom Row ###########-->
    <div class="row">
        <div class="col-md-12">
            <h3>Historical Appraisals</h3>
            <table class="footable table-striped">
                    <thead>
                        <tr>
                            <th data-sort-initial="descending"  data-hide="phone,tablet">Job Number</th>
                            <th  data-class="expand">Property</th>
                            <th data-hide="phone,tablet">Client</th>
                            <th data-hide="phone,tablet" >Appraiser</th>
                            <th class="footable-sortable" data-type="numeric">Due Date</th>
                            <th data-hide="phone,tablet"  class="footable-sortable">Final Value</th>
                            <th data-hide="phone"  class="footable-sortable">Fee</th>
                            <th data-hide="phone,tablet">Status</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for app in hist_apps %}
                        <tr>
                            <td><a href="{{ app.get_absolute_url }}">{{ app.job_number }}</a></td>
                            <td><a href="/property/{{ app.engagement_property.property.id}}">{{ app.engagement_property.property }}</a></td>
                            <td><a href="{{ app.engagement_property.property.client.get_absolute_url }}">{{ app.engagement_property.property.client }}</a></td>
                            <td>{{ app.lead_appraiser.employee.name|default:'' }}</td>
                            <td data-value="{{ app.due_date|date:"Ymd" }}">{{ app.due_date }}</td>
                            <td>${{ app.final_value }}</td>
                            <td>${{ app.fee }}</td>
                            <td>{{ app.get_status_display }}</td>
                        </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
<!--########### End Bottom Row ###########-->
</div>

{% endblock %}

{% block bodyend %}
<script>
    NPVNexus.View_Property.init();
    var coords = []
        {% for add in property.address_set.all %}
        if('{{add.latitude}}' != 'None' && '{{add.longitude}}' != 'None'){
            var c = [{{add.latitude}}, {{add.longitude}}];
            coords.push(c);
        }else{
            //Get Lat and Lon from API
            var geocoder = new google.maps.Geocoder();
            address =("address={{add.address1}},{{add.city}}, {{add.state}}").replace(/ /g ,"+");
            geocoder.geocode( { 'address': address}, function(results, status) {
                if (status == google.maps.GeocoderStatus.OK) {
                    var latitude = results[0].geometry.location.lat();
                    var longitude = results[0].geometry.location.lng(); 
                    console.log("NEED TO SAVE:"+latitude+":"+longitude);
                    var c = [latitude, longitude];
                    coords.push(c);
                } 
            }); 
        }
        {% endfor %}
    //Init MAP
    function initialize() {
        var elm = document.getElementById("MapCanvas");
        NPVNexus.View_Appraisal.setUpMap(elm,coords);
    }
    google.maps.event.addDomListener(window, 'load', initialize);
</script>

{% endblock %}